### ISSUE TITLE
Products are Empty After Upgrading to com.superwall.sdk:superwall-android:1.2.1

### ISSUE THREAD

**Issue by sealtiel92** [superwall/react-native-superwall#10]
I am using @superwall/react-native-superwall with the Android SDK version com.superwall.sdk:superwall-android:1.0.3-beta.1, and everything was working correctly.

However, since Google Play no longer accepts Google Billing v4, I upgraded to com.superwall.sdk:superwall-android:1.2.1, which uses Google Billing v6 as required by Google Play.

After the upgrade, everything else seems to work, but the products are always empty.

This issue does not occur on iOS, where everything works perfectly.

I have reviewed my configuration multiple times, but at this point, I’m not sure what else could be causing this issue.

I also checked the [Superwall's troubleshooting page](https://superwall.com/docs/troubleshooting) but didn't find much help regarding this specific problem.

**Comment by ianrumac** [comment]
Hi @sealtiel92 - it might be due to changes in the Play API itself, resulting in required updates on the Play side too. It's hard to tell exactly without more details about your application/products, so if you want us to take a deeper look feel free to contact us via Intercom on our website - that way you can share that information privately.

In the meantime, have you checked [Google Play's migration guide](https://developer.android.com/google/play/billing/migrate-gpblv6)? It should list the required changes for migrating from v4 to v6.
